### ISSUE TITLE
Non-collection reference properties missing 'add' verb

### ISSUE THREAD

**Issue by kevklam** [microsoftgraph/MSGraph-SDK-Code-Generator#18]
All platforms: XXXReferenceRequest missing 'add' method corresponding to PUT action
On iOS: Entities (and maybe complex types?) are being generated with property types missing "WithReference" where applicable.

Example property: user.manager (see DirectoryObjectReferenceRequest)

**Comment by MIchaelMainer** [comment]
This is fixed in .Net with this commit: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/commit/ae8abf2.
I forget why we chose PUT instead of add.. It may be because add implies adding an object to a collection.  

This issue should remain open as this issue still applies to the Android SDK.
