### ISSUE TITLE
methods from parent entity types are missing in child entity type request builders

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/MSGraph-SDK-Code-Generator#317]
For example https://docs.microsoft.com/en-us/graph/api/group-getmembergroups?view=graph-rest-1.0&tabs=java
 
[AB#7093](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7093)

**Comment by llpop** [comment]
Need some help with the Microsoft Graph API java SDK where I'm trying to get all the AD groups of a particular user. To that extend I've been looking at the https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=http API which hints to the following sample java code:
```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();
Boolean securityEnabledOnly = true;
graphClient.users("someuser@somedomain.com")
	.getMemberGroups(securityEnabledOnly)
	.buildRequest()
	.post();
```
The problem with this is that getMemberGroups does not "exist" and the error is:
```
java: cannot find symbol
  symbol:   method getMemberGroups(java.lang.Boolean)
  location: interface com.microsoft.graph.requests.extensions.IUserRequestBuilder
```

I'm currently using the microsoft-graph 2.6.0 library version (tried with beta 0.3.0-SNAPSHOT as well) & microsoft-graph-auth 0.3.0-SNAPSHOT version.

While using a potential alternative like: `graphClient.directoryObjects("lpop@adobe.com").getMemberGroups(true).buildRequest().post();`
this comes with a caveat where this requires a more elevated permission level of `Directory.Read.All`, as opposed to lower permissions such as `User.Read.All` & `Group.Read.All`.

Since the above is for the user `getMemberGroups` API I'd like to ask for quidance in using the https://docs.microsoft.com/en-us/graph/api/user-checkmembergroups?view=graph-rest-1.0&tabs=http API which has the same problem.

**Comment by baywet** [comment]
Hi @llpop 
Thanks for the feedback.
I've just authored a PR (see #467 and others linked into the PR) to address this issue in our upcoming v3 of the SDK, [more information](https://github.com/microsoftgraph/msgraph-sdk-java/issues/628).

This issue will be closed once the PR gets merged.
