### ISSUE TITLE
Support custom query parameter and header annotations

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/MSGraph-SDK-Code-Generator#361]
Define terms and tooling to support CSDL that defines scenario specific non-OData query parameters and headers.

Currently, this would be useful for calendarview time window definitions. 
[AB#6917](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6917)

**Comment by abheek-das** [comment]
We are adding a new custom query parameter "_includeHiddenFolders=true_" for the _/mailFolder_s entity. Once the API is available in Beta, it would be great if we can ensure that DevX tooling exposes this new custom query capability as well. 

Example Request:
GET https://graph.microsoft.com/beta/me/mailFolders/?includeHiddenFolders=true

Adding this here since query parameters are not present as part of workload metadata CSDL, so it's not possible to pass this info to DevX tooling right now. As suggested offline, we will make sure that code examples in the documentation shows this query parameters.
