### ISSUE TITLE
Reference delete scenario is not supported by the SDK

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/MSGraph-SDK-Code-Generator#471]
There is no generated code available to support:

```http
DELETE /groups/{id}/acceptedSenders/$ref?$id=https://graph.microsoft.com/v1.0/users/{user-id}
```

https://docs.microsoft.com/en-us/graph/api/group-delete-acceptedsenders?view=graph-rest-1.0&tabs=csharp 
[AB#8405](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8405)

**Comment by baywet** [comment]
It should fix it since we have the request builder for it. https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/groups/item/acceptedsenders/ref/ref_request_builder.go

However there does seem to be a bug in the conversion process. https://github.com/microsoft/OpenAPI.NET.OData/issues/128

**Comment by baywet** [comment]
@andrueastman it looks like the snippet is still not being generated for this one.
To me this is either an issue in the conversion process (path segments are not being projected) or in the snippets generation.
Can you validate that specific path is in the description? Based on that, we'll transfer the issue.

**Comment by andrueastman** [comment]
@baywet 
The snippet fails to generate here because there is no DELETE method for `/groups/{group-id}/acceptedSenders/$ref` (only GET and POST). 
The DELETE method, however does exist on the path `/groups/{group-id}/acceptedSenders/{directoryObject-id}/$ref` as is the expectation with [this issue](https://github.com/microsoft/OpenAPI.NET.OData/issues/111) where it's added on the item and not on the collection. 

There may be a conversion issue or a missing annotation that we would need to investigate so that the operation appears on the collection with the relevant query parameter as shown in the snippet.

**Comment by baywet** [comment]
Thanks for reverting here.
I was referring to the first case. Do you think we should transfer this to the metadata repo then?

**Comment by andrueastman** [comment]
After looking into this abit more, this is probably a conversion library issue given the original work/issue [here](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/567) and the PR [here ](https://github.com/microsoft/OpenAPI.NET.OData/pull/112/files) the conversion library looks like it will only add the DELETE operation on the key segment but not on a collection valued one like in the example `~/entityset/{key}/collection-valued-Nav/$ref?$id ={navKey}`

If, it's okay, I'll close this for now and we can follow this one up at https://github.com/microsoft/OpenAPI.NET.OData/issues/453 as this one looks to definitely need conversion library support.
