### ISSUE TITLE
Generation on /beta endpoint doesn't work

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/MSGraph-SDK-Code-Generator#93]
Previous issue https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/89 dated 5/23

It still crashes on the /beta endpoint. How am I supposed to build me a custom Microsoft.Graph for the /beta endpoint if the prerequisite is not up to the job? Nobody else trying to build that? 
[AB#7097](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7097)

**Comment by cbales** [comment]
This issue is actually the result of several other issues:
1.	The Graph API metadata has bugs
a.	We work with teams internally to help promote a valid metadata to v1.0 but are looking to do this earlier so that beta is also available for generation
2.	The generator does not recover from errors
a.	I am currently working on this. You can build beta successfully on the [cbales-working](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/tree/cbales-working) branch if you’d like to try this method. However, although it recovers from errors, the resulting generated files will contain errors reflected from the metadata.
3.	VIPR does not handle capability annotation inheritance correctly
a.	Therefore, in the meantime, we strip out all capability annotations from our metadata
b.	While you will not see any generator or build errors, the resulting library will having missing functionality if you include the annotations
4.	We add custom edits to the metadata that are not currently documented
a.	In the short-term, I will add documentation on these metadata workarounds
b.	Long-term, we need to develop a programmatic strategy for handling these custom edits

To unblock you, I have uploaded a valid [beta metadata document]( https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/master/metadata/beta_2017_07_19.xml) that will allow you to generate against it.

**Comment by christophwille** [comment]
Thanks for the metadata file (works), and also thanks for documenting the necessary manual fixes.
Color me surprised though that the Graph teams themselves are not using vipr as a BVT for their most recent changes on /beta. 
Would it be possible to have an automated package generation (eg for myget publication) that combines the /dev branch from the SDK plus the /beta endpoint from Graph? (breaks and malfunctions would be ok) This would help early adopters enormously.

**Comment by tonipohl** [comment]
Agree, a working SDK for the Beta endpoint would definitely help. Thx!

**Comment by cbales** [comment]
Great feedback. We are currently working on the automation pipeline that will make this a trivial addition. I will keep your feedback in mind as we continue the conversation about adding beta SDK packages.

**Comment by christophwille** [comment]
Any news on the automation pipeline for the beta endpoint / beta SDK?

**Comment by turowicz** [comment]
Any updates on this? @MIchaelMainer @cbales

**Comment by deepak2016** [comment]
@turowicz we are actively working on this work item and will update here once we publish SDK for beta endpoint.

**Comment by zengin** [comment]
this is a stale issue, closing...
